name: SentiSafe
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: '>=2.17.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  location: ^8.0.0
  http: ^1.3.0
  geocoding: ^3.0.0
  shimmer: ^3.0.0
  firebase_messaging: ^15.2.4
  audioplayers: ^6.2.0
  record: ^4.4.4
  camera: ^0.11.1
  flutter_tts: ^4.0.0

  google_maps_flutter: ^2.5.0

  flutter_spinkit: ^5.2.0



  
  
  lottie: ^3.3.1

    # Speech & Notifications
  speech_to_text: ^7.0.0
  flutter_local_notifications: ^18.0.1

  firebase_auth: ^5.5.1
  google_sign_in: ^6.1.6
  shake_detector: ^0.1.2


  timeago: ^3.7.0


    # Firebase dependencies
  firebase_core: ^3.12.1
  cloud_firestore: ^5.6.5

  just_audio: ^0.9.44
 


  url_launcher: ^6.0.0

  # For background service
  flutter_background_service: ^5.0.5
  flutter_background_service_android: ^6.2.2

  # For SMS functionality
  telephony: ^0.2.0



  # For permissions
  permission_handler: ^11.0.1

  image_picker: ^1.1.2
  animated_text_kit: ^4.2.2

  geolocator: ^13.0.2
  flutter_animate: ^4.5.0
  glassmorphism: ^3.0.0


  provider: ^6.1.1
  shared_preferences: ^2.2.2

  intl: ^0.19.0



  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.8
  google_fonts: ^6.2.1
  add_2_calendar: ^3.0.1


dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^5.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:
  assets:
    - assets/img.png
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true




    


  



 